### PR TITLE
Tidied file

### PR DESCRIPTION
**Pull request by petersim-nz**
I realised that I had tidied the wrong file. All should be good now.

### CODE REVIEW

**Comment by TylerGriffin99** [comment]
Dont think I have write access. Am  I meant to confirm the merge to the master after checking the file?

**Comment by petersim-nz** [comment]
I’ll go and make sure that you have it. Need 5 mins.


Sent from Mail for Windows 10

**Comment by petersim-nz** [comment]
I had added you, but you can’t have accepted the invite.
https://github.com/petersim-nz/sprint-2/invitations 

Sent from Mail for Windows 10

**Comment by petersim-nz** [comment]
Yes

Sent from Mail for Windows 10

**Comment by adam-kuhn** [comment]
I had a look as well. Looks good to me!

**Pull request merged**
